name: update_sheet

on:
  workflow_dispatch:
    
  # schedule:
    # - cron: '*/15 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v2

      - name: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: install python packages
        run: |
          make install
      
      - name: executing script
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: |
          mkdir creds
          echo "$TOKEN_JSON" > creds/token.json
          cd src
          python update.py
          cd ..
          rm -rf creds
