name: update_sheet

on:
  schedule:
#    - cron: '0,15,30,45 * * * *'
# Uncomment for running the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v2

      - name: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

